(()=>{'use strict';
const C=document.querySelector('#game'),ctx=C.getContext('2d'),W=C.width,H=C.height,$=s=>document.querySelector(s),T=k=>window.I18N?.t(k)||k;const TOUCH=matchMedia('(pointer:coarse)').matches||('ontouchstart' in window);
const screens=['menu','levels','helpScreen','pause','settings','upgrade','result'];
const LEVELS=[
{name:'Зелёный рубеж',desc:'Лёгкий старт',waves:3,p:['#4f9065','#294b37','#132219'],count:.72,elite:0},
{name:'Пыльный фронт',desc:'Песчаный сектор',waves:4,p:['#aa7a43','#664728','#2d2116'],count:.82,elite:.04},
{name:'Ночной кордон',desc:'Ночной сектор',waves:4,p:['#2a6d83','#173d50','#0b1b24'],count:.9,elite:.07},
{name:'Красная зона',desc:'Тяжёлая броня',waves:5,p:['#66383a','#3a2024','#1a1012'],count:1.02,elite:.12},
{name:'Ледяной периметр',desc:'Плотные волны',waves:5,p:['#477582','#27434b','#122229'],count:1.1,elite:.16},
{name:'Последний рубеж',desc:'Босс',waves:6,p:['#725e3e','#3e3223','#18130e'],count:1.18,elite:.22,boss:true}];
const DIFF={easy:{hp:.68,dmg:.62,n:.72,spd:.9,pd:1.25,heal:1.35},normal:{hp:.82,dmg:.78,n:.84,spd:.94,pd:1.15,heal:1.18},hard:{hp:1.06,dmg:1.04,n:1.04,spd:1.04,pd:1,heal:.9}};
const UPGRADES=[
{id:'damage',code:'DMG',name:'Тяжёлые снаряды',text:'+22% урона',apply:()=>stats.damage*=1.22},
{id:'rate',code:'RPM',name:'Быстрая перезарядка',text:'+20% скорострельности',apply:()=>stats.rate*=.8},
{id:'speed',code:'SPD',name:'Форсаж',text:'+16% скорости',apply:()=>stats.speed*=1.16},
{id:'repair',code:'REP',name:'Полевой ремонт',text:'+28 HP базе',apply:()=>base.hp=Math.min(100,base.hp+28)},
{id:'armor',code:'ARM',name:'Усиленная броня',text:'-18% входящего урона',apply:()=>stats.armor*=.82},
{id:'multi',code:'DBL',name:'Двойной выстрел',text:'Два снаряда за залп',apply:()=>stats.multi=Math.min(3,stats.multi+1)}];
let selected=0,diff='easy',score=0,wave=1,waveTarget=0,spawned=0,killed=0,spawnCd=0,running=false,paused=false,last=0,shake=0,toastTime=0,combo=0,comboTime=0,waveDamage=0;
let save=JSON.parse(localStorage.getItem('tanki_save')||'{"unlocked":1,"best":{},"last":0,"diff":"easy","updatedAt":0}');save.unlocked=Math.max(1,Math.min(LEVELS.length,save.unlocked||1));save.updatedAt=save.updatedAt||0;
let ui=JSON.parse(localStorage.getItem('tanki_settings')||'{"volume":65,"sfx":true,"shake":false,"autopause":true}');
let settingsReturn='menu';
const keys={},bullets=[],enemies=[],parts=[],marks=[],floaters=[],pointer={x:W*.75,y:H*.5,active:false};
const base={x:W/2,y:H/2,r:58,hp:100,flash:0};
const player={x:W/2,y:H/2+155,r:23,a:-Math.PI/2,turret:-Math.PI/2,hp:100,inv:0,cd:0};
let stats={damage:1,rate:1,speed:1,armor:1,multi:1};
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),rand=(a,b)=>a+Math.random()*(b-a);
function screen(id){screens.forEach(x=>$('#'+x).classList.remove('active'));if(id)$('#'+id).classList.add('active');$('#hud').classList.toggle('active',!id)}
function saveNow(){save.last=selected;save.diff=diff;save.updatedAt=Date.now();localStorage.setItem('tanki_save',JSON.stringify(save));Platform.setData?.({tanki_save:save},true).catch?.(()=>{})}
async function syncCloud(){try{const data=await Platform.getData?.(['tanki_save']);const cloud=data?.tanki_save;if(cloud&&typeof cloud==='object'&&(cloud.updatedAt||0)>(save.updatedAt||0)){save={...save,...cloud};save.unlocked=Math.max(1,Math.min(LEVELS.length,save.unlocked||1));localStorage.setItem('tanki_save',JSON.stringify(save))}else if(save.updatedAt){Platform.setData?.({tanki_save:save},true).catch?.(()=>{})}}catch(e){}}
function saveUi(){localStorage.setItem('tanki_settings',JSON.stringify(ui))}
function applyUi(){
  $('#volumeRange').value=ui.volume??65;if($('#volumeValue'))$('#volumeValue').textContent=(ui.volume??65)+'%';
  $('#sfxToggle').classList.toggle('active',!!ui.sfx);$('#sfxToggle').textContent=ui.sfx?T('on'):T('off');
  $('#shakeToggle').classList.toggle('active',!!ui.shake);$('#shakeToggle').textContent=ui.shake?T('on'):T('off');
  $('#autopauseToggle').classList.toggle('active',!!ui.autopause);$('#autopauseToggle').textContent=ui.autopause?T('on'):T('off');
  AudioFX?.setEnabled(!!ui.sfx);AudioFX?.setVolume((ui.volume??65)/100);
}
function openSettings(from){settingsReturn=from||'menu';screen('settings');applyUi()}
function closeSettings(){screen(settingsReturn)}
function renderLevels(){const g=$('#levelGrid');g.innerHTML='';LEVELS.forEach((l,i)=>{const locked=i>=save.unlocked,st=save.best[i]?.stars||0,d=document.createElement('div'),name=T('level.'+i+'.name'),desc=T('level.'+i+'.desc');d.className='levelCard'+(i===selected?' selected':'')+(locked?' locked':'');d.innerHTML=`<div class="stars">${'★'.repeat(st)}${'☆'.repeat(3-st)}</div><small>${T('level.word')} ${i+1}</small><strong>${name}</strong><small>${desc}<br>${l.waves} ${T('waves.word')}</small>`;if(!locked)d.onclick=()=>{selected=i;renderLevels();hud()};g.appendChild(d)});$('#launch').disabled=selected>=save.unlocked}
function setDiff(d){diff=d;document.querySelectorAll('[data-diff]').forEach(x=>x.classList.toggle('active',x.dataset.diff===d))}
function hud(){const rem=Math.max(0,waveTarget-killed),bh=clamp(base.hp,0,100),th=clamp(player.hp,0,100);$('#score').textContent=score;$('#wave').textContent=wave;$('#maxWave').textContent=LEVELS[selected].waves;$('#remain').textContent=rem;$('#baseHp').textContent=Math.max(0,Math.round(bh));$('#tankHp').textContent=Math.max(0,Math.round(th));$('#baseBar').style.width=bh+'%';$('#tankBar').style.width=th+'%';const bv=$('.baseVital'),tv=$('.tankVital');if(bv){bv.classList.toggle('warning',bh<60&&bh>=30);bv.classList.toggle('critical',bh<30)}if(tv){tv.classList.toggle('warning',th<60&&th>=30);tv.classList.toggle('critical',th<30)}}
function toast(t,s=1){$('#toast').textContent=t;$('#toast').style.opacity=1;toastTime=s}
function reset(){score=0;wave=1;spawned=0;killed=0;spawnCd=.5;combo=0;comboTime=0;waveDamage=0;stats={damage:1,rate:1,speed:1,armor:1,multi:1};bullets.length=enemies.length=parts.length=marks.length=floaters.length=0;base.hp=100;player.hp=100;player.x=W/2;player.y=H/2+155;player.inv=0;player.cd=0;waveTarget=targetCount();hud()}
function targetCount(){const l=LEVELS[selected],d=DIFF[diff];return Math.max(4,Math.round((4+selected*.9+wave*1.2)*l.count*d.n))}
function particle(x,y,color,n=8,p=170){for(let i=0;i<n;i++){const a=rand(0,Math.PI*2),s=rand(p*.2,p);parts.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:rand(.25,.65),m:.65,size:rand(2,6),color})}}
function boom(x,y,big=false){particle(x,y,big?'#ffd464':'#ff946b',big?30:10,big?340:180);if(ui.shake)shake=Math.max(shake,big?11:4);AudioFX?.explosion(big)}
function shoot(){if(!running||paused||player.cd>0)return;AudioFX?.shoot();player.cd=.15*stats.rate;const spread=stats.multi===1?[0]:stats.multi===2?[-.045,.045]:[-.07,0,.07];for(const s of spread){const a=player.turret+s,x=player.x+Math.cos(a)*34,y=player.y+Math.sin(a)*34;bullets.push({x,y,vx:Math.cos(a)*700,vy:Math.sin(a)*700,r:4,life:1.7,enemy:false,dmg:38*DIFF[diff].pd*stats.damage})}particle(player.x+Math.cos(player.turret)*34,player.y+Math.sin(player.turret)*34,'#f5ffa1',7,120)}
function type(){const l=LEVELS[selected],r=Math.random();if(l.boss&&wave===l.waves&&spawned===waveTarget-1)return'boss';if(wave>=3&&r<l.elite)return'elite';if(wave>=2&&r<.25)return'fast';if(wave>=2&&r<.48)return'heavy';return'normal'}
function spawn(){const d=DIFF[diff],a=rand(0,Math.PI*2),rad=rand(490,570),t=type();if(t==='boss'){toast(T('toast.boss'),1.4);AudioFX?.boss()}let c=t==='boss'?{r:38,hp:600,spd:40,cd:.8,dmg:17,col:'#a9523d',reward:1000}:t==='elite'?{r:27,hp:145,spd:68,cd:1,dmg:13,col:'#934660',reward:280}:t==='heavy'?{r:28,hp:120,spd:57,cd:1.3,dmg:12,col:'#805044',reward:210}:t==='fast'?{r:19,hp:46,spd:110,cd:1,dmg:8,col:'#a77135',reward:150}:{r:22,hp:68,spd:78,cd:1.2,dmg:9,col:'#7d4348',reward:120};c.hp*=d.hp;c.spd*=d.spd;c.dmg*=d.dmg;enemies.push({x:clamp(base.x+Math.cos(a)*rad,25,W-25),y:clamp(base.y+Math.sin(a)*rad,25,H-25),r:c.r,hp:c.hp,max:c.hp,spd:c.spd,cd:rand(.5,1.2),fire:c.cd,dmg:c.dmg,col:c.col,reward:c.reward,type:t,a:a+Math.PI,turret:a+Math.PI,hit:0});spawned++;hud()}
function kill(e){const i=enemies.indexOf(e);if(i<0)return;enemies.splice(i,1);killed++;combo=comboTime>0?combo+1:1;comboTime=2.2;const mult=Math.min(3,1+(combo-1)*.15),gain=Math.round(e.reward*mult);score+=gain;floaters.push({x:e.x,y:e.y-18,text:'+'+gain,color:'#efff83',life:1,m:1,size:17});if(combo>=2){const cp=$('#comboPill');cp.textContent='КОМБО ×'+combo;cp.classList.add('show')}boom(e.x,e.y,true);hud();if(killed>=waveTarget&&enemies.length===0){if(waveDamage===0){const bonus=150*wave;score+=bonus;hud();toast(T('toast.perfect')+' +'+bonus,1.15);floaters.push({x:base.x,y:base.y-80,text:'PERFECT +'+bonus,color:'#dfff77',life:1.35,m:1.35,size:22})}if(wave>=LEVELS[selected].waves)setTimeout(()=>finish(true),650);else setTimeout(showUpgrade,700)}}
function showUpgrade(){running=false;Platform.stop();const pool=[...UPGRADES].sort(()=>Math.random()-.5).slice(0,3),g=$('#upgradeGrid');g.innerHTML='';pool.forEach(u=>{const b=document.createElement('button');b.className='upgradeCard upgrade-'+u.id;b.innerHTML=`<div class="upgradeTop"><em>${u.code}</em><span class="upgradeArrow">→</span></div><b>${T('up.'+u.id+'.name')}</b><span class="upgradeText">${T('up.'+u.id+'.text')}</span>`;b.onclick=()=>{AudioFX?.upgrade();u.apply();wave++;spawned=killed=0;waveDamage=0;waveTarget=targetCount();base.hp=Math.min(100,base.hp+14*DIFF[diff].heal);player.hp=Math.min(100,player.hp+22);screen(null);running=true;spawnCd=.55;toast(T('wave')+' '+wave,1);AudioFX?.wave();hud();Platform.start()};g.appendChild(b)});screen('upgrade')}
function finish(win){running=false;Platform.stop();if(win)AudioFX?.win();else AudioFX?.lose();$('#rScore').textContent=score;$('#rWave').textContent=wave;$('#rBase').textContent=Math.max(0,Math.round(base.hp))+'%';if(win){const stars=base.hp>=75?3:base.hp>=40?2:1;$('#resultTitle').textContent=T('victory');$('#resultText').textContent=`${T('level.'+selected+'.name')} · ${'★'.repeat(stars)}${'☆'.repeat(3-stars)}`;save.best[selected]={stars:Math.max(stars,save.best[selected]?.stars||0),score:Math.max(score,save.best[selected]?.score||0)};save.unlocked=Math.max(save.unlocked,Math.min(LEVELS.length,selected+2));saveNow();$('#next').style.display=selected<LEVELS.length-1?'block':'none'}else{$('#resultTitle').textContent=T('defeat');$('#resultText').textContent=T('defeat.text');$('#next').style.display='none'}screen('result')}
function start(){AudioFX?.unlock();AudioFX?.wave();reset();screen(null);running=true;paused=false;toast(T('toast.defend'),1.1);Platform.start()}
function pauseGame(){if(!running)return;paused=true;screen('pause');Platform.stop()}function resumeGame(){paused=false;screen(null);Platform.start()}
function hurtBase(v){base.hp-=v;waveDamage+=v;base.flash=.15;if(ui.shake)shake=7;hud();if(base.hp<=0)finish(false)}function hurtPlayer(v){if(player.inv>0)return;player.hp-=v*stats.armor;player.inv=.5;if(ui.shake)shake=5;if(player.hp<=0){player.hp=35;player.x=base.x;player.y=base.y+165;player.inv=2;toast(T('toast.tankback'),.9)}hud()}
function update(dt){if(toastTime>0&&(toastTime-=dt)<=0)$('#toast').style.opacity=0;if(comboTime>0&&(comboTime-=dt)<=0){combo=0;$('#comboPill').classList.remove('show')}for(const f of floaters){f.life-=dt;f.y-=30*dt}for(let i=floaters.length-1;i>=0;i--)if(floaters[i].life<=0)floaters.splice(i,1);shake=Math.max(0,shake-dt*25);base.flash=Math.max(0,base.flash-dt);for(const p of parts){p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=Math.pow(.05,dt);p.vy*=Math.pow(.05,dt)}for(let i=parts.length-1;i>=0;i--)if(parts[i].life<=0)parts.splice(i,1);if(!running||paused)return;base.hp=Math.min(100,base.hp+dt*.55);player.cd=Math.max(0,player.cd-dt);player.inv=Math.max(0,player.inv-dt);let mx=(keys.ArrowRight||keys.KeyD?1:0)-(keys.ArrowLeft||keys.KeyA?1:0),my=(keys.ArrowDown||keys.KeyS?1:0)-(keys.ArrowUp||keys.KeyW?1:0);if(mx||my){const l=Math.hypot(mx,my);mx/=l;my/=l;player.a=Math.atan2(my,mx);player.x=clamp(player.x+mx*255*stats.speed*dt,28,W-28);player.y=clamp(player.y+my*255*stats.speed*dt,28,H-28);const db=Math.hypot(player.x-base.x,player.y-base.y);if(db<base.r+player.r+12){const a=Math.atan2(player.y-base.y,player.x-base.x);player.x=base.x+Math.cos(a)*(base.r+player.r+12);player.y=base.y+Math.sin(a)*(base.r+player.r+12)}}if(TOUCH&&enemies.length){let target=enemies[0],best=Infinity;for(const e of enemies){const d=(e.x-player.x)**2+(e.y-player.y)**2;if(d<best){best=d;target=e}}pointer.x=target.x;pointer.y=target.y;pointer.active=false;player.turret=Math.atan2(target.y-player.y,target.x-player.x);if(player.cd<=0)shoot()}else{player.turret=Math.atan2(pointer.y-player.y,pointer.x-player.x)}if(spawned<waveTarget&&(spawnCd-=dt)<=0){spawn();spawnCd=Math.max(.52,1.25-wave*.04-selected*.02)}for(const e of enemies){e.hit=Math.max(0,e.hit-dt);e.cd-=dt;const dx=base.x-e.x,dy=base.y-e.y,d=Math.max(1,Math.hypot(dx,dy)),pd=Math.hypot(player.x-e.x,player.y-e.y),tp=pd<190&&e.type!=='boss'?player:base,tx=tp.x-e.x,ty=tp.y-e.y,td=Math.max(1,Math.hypot(tx,ty));e.turret=Math.atan2(ty,tx);if(d>base.r+(e.type==='boss'?130:100)){e.x+=dx/d*e.spd*dt;e.y+=dy/d*e.spd*dt;e.a=Math.atan2(dy,dx)}if(e.cd<=0&&td<390){e.cd=e.fire*rand(.9,1.25);const a=e.turret+rand(-.07,.07);bullets.push({x:e.x+Math.cos(a)*30,y:e.y+Math.sin(a)*30,vx:Math.cos(a)*370,vy:Math.sin(a)*370,r:e.type==='boss'?7:5,life:2,enemy:true,dmg:e.dmg})}}for(const b of bullets){b.life-=dt;b.x+=b.vx*dt;b.y+=b.vy*dt;if(b.enemy){if((b.x-base.x)**2+(b.y-base.y)**2<(b.r+base.r)**2){b.life=0;hurtBase(b.dmg)}else if((b.x-player.x)**2+(b.y-player.y)**2<(b.r+player.r)**2){b.life=0;hurtPlayer(b.dmg)}}else for(const e of enemies)if((b.x-e.x)**2+(b.y-e.y)**2<(b.r+e.r)**2){b.life=0;e.hp-=b.dmg;e.hit=.1;AudioFX?.hit();floaters.push({x:b.x,y:b.y-8,text:'-'+Math.round(b.dmg),color:'#fff0b0',life:.55,m:.55,size:13});particle(b.x,b.y,'#fff1a7',7,145);if(e.hp<=0)kill(e);break}}for(let i=bullets.length-1;i>=0;i--){const b=bullets[i];if(b.life<=0||b.x<-20||b.x>W+20||b.y<-20||b.y>H+20)bullets.splice(i,1)}}
function rr(x,y,w,h,r){ctx.beginPath();ctx.roundRect(x,y,w,h,r)}
function tank(t,enemy){ctx.save();ctx.translate(t.x,t.y);ctx.shadowColor='#0008';ctx.shadowBlur=14;ctx.shadowOffsetY=7;ctx.save();ctx.rotate(t.a);ctx.fillStyle='#101619';rr(-t.r-5,-t.r*.72,t.r*2+10,t.r*1.44,8);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle=enemy?t.col:'#46aa78';rr(-t.r,-t.r*.56,t.r*2,t.r*1.12,7);ctx.fill();ctx.fillStyle='#0c1113';ctx.fillRect(-t.r-4,-t.r*.77,t.r*2+8,5);ctx.fillRect(-t.r-4,t.r*.57,t.r*2+8,5);ctx.restore();ctx.rotate(t.turret);ctx.fillStyle=enemy?(t.hit>0?'#ffe7d6':'#d86f63'):'#a8ee8f';rr(0,-5,t.r+24,10,4);ctx.fill();ctx.beginPath();ctx.arc(0,0,t.r*.58,0,Math.PI*2);ctx.fill();ctx.restore();if(enemy){ctx.fillStyle='#0008';rr(t.x-22,t.y-t.r-14,44,5,3);ctx.fill();ctx.fillStyle=eColor(t.type);rr(t.x-22,t.y-t.r-14,44*clamp(t.hp/t.max,0,1),5,3);ctx.fill()}}
function eColor(t){return t==='boss'?'#ffc45f':t==='elite'?'#ff87b0':t==='fast'?'#ffd45f':'#ff7b70'}
function draw(){const l=LEVELS[selected],g=ctx.createRadialGradient(base.x,base.y,20,base.x,base.y,720);g.addColorStop(0,l.p[0]);g.addColorStop(.58,l.p[1]);g.addColorStop(1,l.p[2]);ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.save();ctx.translate(ui.shake&&shake?rand(-shake,shake):0,ui.shake&&shake?rand(-shake,shake):0);ctx.strokeStyle='#ffffff08';ctx.lineWidth=1;for(let x=0;x<W;x+=64){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,H);ctx.stroke()}for(let y=0;y<H;y+=64){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()}
ctx.globalAlpha=1;ctx.save();ctx.translate(base.x,base.y);ctx.shadowColor='#0008';ctx.shadowBlur=25;ctx.fillStyle='#233339';ctx.beginPath();ctx.arc(0,0,70,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.strokeStyle='#596d6f';ctx.lineWidth=10;ctx.beginPath();ctx.arc(0,0,57,0,Math.PI*2);ctx.stroke();ctx.fillStyle=base.flash>0?'#fff0ad':'#65866f';ctx.beginPath();ctx.arc(0,0,43,0,Math.PI*2);ctx.fill();ctx.fillStyle='#e8ff76';rr(-7,-42,14,29,5);ctx.fill();ctx.restore();for(const b of bullets){ctx.fillStyle=b.enemy?'#ff9d78':'#f8ffa3';ctx.shadowBlur=13;ctx.shadowColor=ctx.fillStyle;ctx.beginPath();ctx.arc(b.x,b.y,b.r,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0}for(const e of enemies){if(e.type==='boss'){ctx.strokeStyle='#ff745477';ctx.lineWidth=3;ctx.beginPath();ctx.arc(e.x,e.y,e.r+13+Math.sin(performance.now()/130)*3,0,Math.PI*2);ctx.stroke()}tank(e,true)}tank(player,false);for(const p of parts){ctx.globalAlpha=clamp(p.life/p.m,0,1);ctx.fillStyle=p.color;ctx.fillRect(p.x-p.size/2,p.y-p.size/2,p.size,p.size)}ctx.globalAlpha=1;for(const f of floaters){ctx.save();ctx.globalAlpha=clamp(f.life/f.m,0,1);ctx.fillStyle=f.color;ctx.font='900 '+f.size+'px Inter,system-ui,sans-serif';ctx.textAlign='center';ctx.shadowColor='#000';ctx.shadowBlur=5;ctx.fillText(f.text,f.x,f.y);ctx.restore()}if(pointer.active&&running){ctx.strokeStyle='#e7ff9bdc';ctx.lineWidth=2;ctx.beginPath();ctx.arc(pointer.x,pointer.y,10,0,Math.PI*2);ctx.moveTo(pointer.x-16,pointer.y);ctx.lineTo(pointer.x+16,pointer.y);ctx.moveTo(pointer.x,pointer.y-16);ctx.lineTo(pointer.x,pointer.y+16);ctx.stroke()}ctx.restore();const v=ctx.createRadialGradient(W/2,H/2,260,W/2,H/2,780);v.addColorStop(.55,'#0000');v.addColorStop(1,'#0006');ctx.fillStyle=v;ctx.fillRect(0,0,W,H)}
function loop(t){const dt=Math.min(.033,(t-last)/1000||0);last=t;update(dt);draw();requestAnimationFrame(loop)}
function pos(e){const r=C.getBoundingClientRect();return{x:(e.clientX-r.left)/r.width*W,y:(e.clientY-r.top)/r.height*H}}
addEventListener('keydown',e=>{keys[e.code]=1;if(e.code==='Space'){e.preventDefault();shoot()}if(e.code==='Escape'){if(running&&!paused)pauseGame();else if(paused)resumeGame()}});addEventListener('keyup',e=>keys[e.code]=0);C.addEventListener('mousemove',e=>Object.assign(pointer,pos(e),{active:true}));C.addEventListener('mousedown',e=>{Object.assign(pointer,pos(e),{active:true});if(e.button===0)shoot()});C.addEventListener('contextmenu',e=>e.preventDefault());C.addEventListener('touchstart',e=>{if(e.touches[0])Object.assign(pointer,pos(e.touches[0]),{active:true})},{passive:true});C.addEventListener('touchmove',e=>{if(e.touches[0])Object.assign(pointer,pos(e.touches[0]),{active:true})},{passive:true});document.querySelectorAll('.pad button').forEach(b=>{const k=b.dataset.k;b.onpointerdown=e=>{e.preventDefault();keys[k]=1};b.onpointerup=b.onpointercancel=b.onpointerleave=e=>{e.preventDefault();keys[k]=0}});$('#fire').onpointerdown=e=>{e.preventDefault();shoot()};
$('#settingsBtn').onclick=()=>openSettings('menu');$('#pauseSettings').onclick=()=>openSettings('pause');$('#settingsBack').onclick=closeSettings;$('#volumeRange').oninput=e=>{ui.volume=+e.target.value;saveUi();applyUi()};$('#sfxToggle').onclick=()=>{ui.sfx=!ui.sfx;saveUi();applyUi()};$('#shakeToggle').onclick=()=>{ui.shake=!ui.shake;saveUi();applyUi()};$('#autopauseToggle').onclick=()=>{ui.autopause=!ui.autopause;saveUi();applyUi()};$('#play').onclick=()=>{selected=Math.min(save.unlocked-1,save.last||0);setDiff(save.diff||'easy');renderLevels();screen('levels')};$('#quick').onclick=()=>{selected=Math.min(save.unlocked-1,save.last||0);setDiff(save.diff||'easy');start()};$('#help').onclick=()=>screen('helpScreen');$('#helpBack').onclick=()=>screen('menu');$('#back').onclick=()=>screen('menu');document.querySelectorAll('[data-diff]').forEach(b=>b.onclick=()=>{setDiff(b.dataset.diff);saveNow()});$('#launch').onclick=start;$('#pauseBtn').onclick=pauseGame;$('#resume').onclick=resumeGame;$('#restart').onclick=start;$('#quit').onclick=()=>{saveNow();running=false;paused=false;Platform.stop();screen('menu')};$('#retry').onclick=start;$('#resultMenu').onclick=()=>{renderLevels();screen('levels')};$('#next').onclick=()=>{selected=Math.min(LEVELS.length-1,selected+1);start()};document.addEventListener('visibilitychange',()=>{if(document.hidden){AudioFX?.suspend();Platform.stop();if(ui.autopause&&running&&!paused)pauseGame()}else{AudioFX?.resume();if(running&&!paused)Platform.start()}});window.addEventListener('yandex-game-pause',()=>{AudioFX?.suspend();if(running&&!paused)pauseGame();else Platform.stop()});window.addEventListener('yandex-game-resume',()=>{AudioFX?.resume();if(running&&!paused)Platform.start()});
(async()=>{await Platform.init();I18N?.setLanguage(Platform.language());await syncCloud();selected=Math.min(save.unlocked-1,save.last||0);setDiff(save.diff||'easy');I18N?.apply();applyUi();renderLevels();hud();draw();Platform.ready();requestAnimationFrame(loop)})();
})();